# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_1_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_1_mix_roformer_256.zip --output-json 10fold_b_json/10fold_1_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_2_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_2_mix_roformer_256.zip --output-json 10fold_b_json/10fold_2_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_3_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_3_mix_roformer_256.zip --output-json 10fold_b_json/10fold_3_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_4_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_4_mix_roformer_256.zip --output-json 10fold_b_json/10fold_4_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_5_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_5_mix_roformer_256.zip --output-json 10fold_b_json/10fold_5_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_6_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_6_mix_roformer_256.zip --output-json 10fold_b_json/10fold_6_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_7_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_7_mix_roformer_256.zip --output-json 10fold_b_json/10fold_7_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_8_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_8_mix_roformer_256.zip --output-json 10fold_b_json/10fold_8_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_9_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_9_mix_roformer_256.zip --output-json 10fold_b_json/10fold_9_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_10_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_10_mix_roformer_256.zip --output-json 10fold_b_json/10fold_10_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_11_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_11_mix_roformer_256.zip --output-json 10fold_b_json/10fold_11_mix_roformer_256.json

# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/ft_uniter_mlm_mean_3000/ckpt-3014 --output-zip 10fold_b_zip/10fold_1_uniter_mlm_mean.zip 

# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_1_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_1_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_1_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_2_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_2_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_2_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_3_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_3_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_3_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_4_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_4_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_4_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_5_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_5_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_5_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_6_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_6_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_6_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_7_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_7_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_7_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_8_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_8_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_8_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_9_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_9_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_9_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_10_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_10_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_10_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_11_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_11_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_11_uniter_mlm_tag_mean_kl.json

# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_1_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_1_mix_addtf.zip --output-json 10fold_b_json/10fold_1_mix_addtf.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_2_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_2_mix_addtf.zip --output-json 10fold_b_json/10fold_2_mix_addtf.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_3_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_3_mix_addtf.zip --output-json 10fold_b_json/10fold_3_mix_addtf.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_4_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_4_mix_addtf.zip --output-json 10fold_b_json/10fold_4_mix_addtf.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_5_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_5_mix_addtf.zip --output-json 10fold_b_json/10fold_5_mix_addtf.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_6_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_6_mix_addtf.zip --output-json 10fold_b_json/10fold_6_mix_addtf.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_7_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_7_mix_addtf.zip --output-json 10fold_b_json/10fold_7_mix_addtf.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_8_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_8_mix_addtf.zip --output-json 10fold_b_json/10fold_8_mix_addtf.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_9_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_9_mix_addtf.zip --output-json 10fold_b_json/10fold_9_mix_addtf.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_10_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_10_mix_addtf.zip --output-json 10fold_b_json/10fold_10_mix_addtf.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_11_mix_addtf/ckpt-4012 --output-zip 10fold_b_zip/10fold_11_mix_addtf.zip --output-json 10fold_b_json/10fold_11_mix_addtf.json

# CUDA_VISIBLE_DEVICES=0 python inference_pair_b.py --ckpt-file save/10fold_1_mix_nextsoft_filter/ckpt-4012 --vlad-cluster-size 4000 --vlad-groups 4 --output-zip 10fold_b_zip/filter_mix_nextsoft.zip 

# CUDA_VISIBLE_DEVICES=1 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/filter15_1_uniter_mlm_tag_mean_kl/ckpt-3015 --output-zip 10fold_b_zip/filter15_1_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/filter15_1_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=1 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/filter15_2_uniter_mlm_tag_mean_kl/ckpt-3015 --output-zip 10fold_b_zip/filter15_2_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/filter15_2_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=1 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/filter15_3_uniter_mlm_tag_mean_kl/ckpt-3015 --output-zip 10fold_b_zip/filter15_3_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/filter15_3_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=1 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/filter15_4_uniter_mlm_tag_mean_kl/ckpt-3015 --output-zip 10fold_b_zip/filter15_4_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/filter15_4_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=1 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/filter15_5_uniter_mlm_tag_mean_kl/ckpt-3015 --output-zip 10fold_b_zip/filter15_5_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/filter15_5_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=1 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/filter15_6_uniter_mlm_tag_mean_kl/ckpt-3015 --output-zip 10fold_b_zip/filter15_6_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/filter15_6_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=1 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/filter15_7_uniter_mlm_tag_mean_kl/ckpt-3015 --output-zip 10fold_b_zip/filter15_7_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/filter15_7_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=1 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/filter15_8_uniter_mlm_tag_mean_kl/ckpt-3015 --output-zip 10fold_b_zip/filter15_8_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/filter15_8_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=1 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/filter15_9_uniter_mlm_tag_mean_kl/ckpt-3015 --output-zip 10fold_b_zip/filter15_9_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/filter15_9_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=1 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/filter15_10_uniter_mlm_tag_mean_kl/ckpt-3015 --output-zip 10fold_b_zip/filter15_10_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/filter15_10_uniter_mlm_tag_mean_kl.json

# CUDA_VISIBLE_DEVICES=2 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_1_uniter_mlm_tag_mean_kl_mlm/ckpt-4013 --output-zip 10fold_b_zip/10fold_1_uniter_mlm_tag_mean_kl_mlm.zip 

# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --bert-seq-len 60 --ckpt-file save/10fold/10fold_1_mix_60/ckpt-4012 --output-zip 10fold_b_zip/10fold_1_mix_60.zip --output-json 10fold_b_json/10fold_1_mix_60.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --bert-seq-len 60 --ckpt-file save/10fold/10fold_2_mix_60/ckpt-4012 --output-zip 10fold_b_zip/10fold_2_mix_60.zip --output-json 10fold_b_json/10fold_2_mix_60.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --bert-seq-len 60 --ckpt-file save/10fold/10fold_3_mix_60/ckpt-4012 --output-zip 10fold_b_zip/10fold_3_mix_60.zip --output-json 10fold_b_json/10fold_3_mix_60.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --bert-seq-len 60 --ckpt-file save/10fold/10fold_4_mix_60/ckpt-4012 --output-zip 10fold_b_zip/10fold_4_mix_60.zip --output-json 10fold_b_json/10fold_4_mix_60.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --bert-seq-len 60 --ckpt-file save/10fold/10fold_5_mix_60/ckpt-4012 --output-zip 10fold_b_zip/10fold_5_mix_60.zip --output-json 10fold_b_json/10fold_5_mix_60.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --bert-seq-len 60 --ckpt-file save/10fold/10fold_6_mix_60/ckpt-4012 --output-zip 10fold_b_zip/10fold_6_mix_60.zip --output-json 10fold_b_json/10fold_6_mix_60.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --bert-seq-len 60 --ckpt-file save/10fold/10fold_7_mix_60/ckpt-4012 --output-zip 10fold_b_zip/10fold_7_mix_60.zip --output-json 10fold_b_json/10fold_7_mix_60.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --bert-seq-len 60 --ckpt-file save/10fold/10fold_8_mix_60/ckpt-4012 --output-zip 10fold_b_zip/10fold_8_mix_60.zip --output-json 10fold_b_json/10fold_8_mix_60.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --bert-seq-len 60 --ckpt-file save/10fold/10fold_9_mix_60/ckpt-4012 --output-zip 10fold_b_zip/10fold_9_mix_60.zip --output-json 10fold_b_json/10fold_9_mix_60.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --bert-seq-len 60 --ckpt-file save/10fold/10fold_10_mix_60/ckpt-4012 --output-zip 10fold_b_zip/10fold_10_mix_60.zip --output-json 10fold_b_json/10fold_10_mix_60.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --bert-seq-len 60 --ckpt-file save/10fold/10fold_11_mix_60/ckpt-4012 --output-zip 10fold_b_zip/10fold_11_mix_60.zip --output-json 10fold_b_json/10fold_11_mix_60.json

# asl 训得时候忘记改名了
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_1_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_1_uniter_mlm_tag_mean_kl_asl.zip --output-json 10fold_b_json/10fold_1_uniter_mlm_tag_mean_kl_asl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_2_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_2_uniter_mlm_tag_mean_kl_asl.zip --output-json 10fold_b_json/10fold_2_uniter_mlm_tag_mean_kl_asl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_3_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_3_uniter_mlm_tag_mean_kl_asl.zip --output-json 10fold_b_json/10fold_3_uniter_mlm_tag_mean_kl_asl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_4_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_4_uniter_mlm_tag_mean_kl_asl.zip --output-json 10fold_b_json/10fold_4_uniter_mlm_tag_mean_kl_asl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_5_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_5_uniter_mlm_tag_mean_kl_asl.zip --output-json 10fold_b_json/10fold_5_uniter_mlm_tag_mean_kl_asl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_6_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_6_uniter_mlm_tag_mean_kl_asl.zip --output-json 10fold_b_json/10fold_6_uniter_mlm_tag_mean_kl_asl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_7_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_7_uniter_mlm_tag_mean_kl_asl.zip --output-json 10fold_b_json/10fold_7_uniter_mlm_tag_mean_kl_asl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_8_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_8_uniter_mlm_tag_mean_kl_asl.zip --output-json 10fold_b_json/10fold_8_uniter_mlm_tag_mean_kl_asl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_9_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_9_uniter_mlm_tag_mean_kl_asl.zip --output-json 10fold_b_json/10fold_9_uniter_mlm_tag_mean_kl_asl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_10_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_10_uniter_mlm_tag_mean_kl_asl.zip --output-json 10fold_b_json/10fold_10_uniter_mlm_tag_mean_kl_asl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_11_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_11_uniter_mlm_tag_mean_kl_asl.zip --output-json 10fold_b_json/10fold_11_uniter_mlm_tag_mean_kl_asl.json

# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_roformer_b.py --bert-dir junnyu/roformer_chinese_base --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_1_uniter_mlm_tag_mean_kl_roformer/ckpt-4013 --output-zip 10fold_b_zip/10fold_1_uniter_mlm_tag_mean_kl_roformer.zip #--output-json 10fold_b_json/10fold_1_uniter_mlm_tag_mean_kl_roformer.json
# CUDA_VISIBLE_DEVICES=1 python inference_pair_b.py --bert-seq-len 32 --ckpt-file save/mix_rank/ckpt-4014 --output-zip 10fold_b_zip/ft_mix_rank.zip #--output-json 10fold_b_json/10fold_1_mix_60.json

# CUDA_VISIBLE_DEVICES=2 python inference_pair_uniter_roformer_b.py --bert-dir junnyu/roformer_chinese_base --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_1_uniter_mlm_tag_mean_kl_roformer/ckpt-4013 --output-zip 10fold_b_zip/10fold_1_uniter_mlm_tag_mean_kl_roformer.zip --output-json 10fold_b_json/10fold_1_uniter_mlm_tag_mean_kl_roformer.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_uniter_roformer_b.py --bert-dir junnyu/roformer_chinese_base --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_2_uniter_mlm_tag_mean_kl_roformer/ckpt-4013 --output-zip 10fold_b_zip/10fold_2_uniter_mlm_tag_mean_kl_roformer.zip --output-json 10fold_b_json/10fold_2_uniter_mlm_tag_mean_kl_roformer.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_uniter_roformer_b.py --bert-dir junnyu/roformer_chinese_base --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_3_uniter_mlm_tag_mean_kl_roformer/ckpt-4013 --output-zip 10fold_b_zip/10fold_3_uniter_mlm_tag_mean_kl_roformer.zip --output-json 10fold_b_json/10fold_3_uniter_mlm_tag_mean_kl_roformer.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_uniter_roformer_b.py --bert-dir junnyu/roformer_chinese_base --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_4_uniter_mlm_tag_mean_kl_roformer/ckpt-4013 --output-zip 10fold_b_zip/10fold_4_uniter_mlm_tag_mean_kl_roformer.zip --output-json 10fold_b_json/10fold_4_uniter_mlm_tag_mean_kl_roformer.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_uniter_roformer_b.py --bert-dir junnyu/roformer_chinese_base --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_5_uniter_mlm_tag_mean_kl_roformer/ckpt-4013 --output-zip 10fold_b_zip/10fold_5_uniter_mlm_tag_mean_kl_roformer.zip --output-json 10fold_b_json/10fold_5_uniter_mlm_tag_mean_kl_roformer.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_uniter_roformer_b.py --bert-dir junnyu/roformer_chinese_base --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_6_uniter_mlm_tag_mean_kl_roformer/ckpt-4013 --output-zip 10fold_b_zip/10fold_6_uniter_mlm_tag_mean_kl_roformer.zip --output-json 10fold_b_json/10fold_6_uniter_mlm_tag_mean_kl_roformer.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_uniter_roformer_b.py --bert-dir junnyu/roformer_chinese_base --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_7_uniter_mlm_tag_mean_kl_roformer/ckpt-4013 --output-zip 10fold_b_zip/10fold_7_uniter_mlm_tag_mean_kl_roformer.zip --output-json 10fold_b_json/10fold_7_uniter_mlm_tag_mean_kl_roformer.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_uniter_roformer_b.py --bert-dir junnyu/roformer_chinese_base --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_8_uniter_mlm_tag_mean_kl_roformer/ckpt-4013 --output-zip 10fold_b_zip/10fold_8_uniter_mlm_tag_mean_kl_roformer.zip --output-json 10fold_b_json/10fold_8_uniter_mlm_tag_mean_kl_roformer.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_uniter_roformer_b.py --bert-dir junnyu/roformer_chinese_base --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_9_uniter_mlm_tag_mean_kl_roformer/ckpt-4013 --output-zip 10fold_b_zip/10fold_9_uniter_mlm_tag_mean_kl_roformer.zip --output-json 10fold_b_json/10fold_9_uniter_mlm_tag_mean_kl_roformer.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_uniter_roformer_b.py --bert-dir junnyu/roformer_chinese_base --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_10_uniter_mlm_tag_mean_kl_roformer/ckpt-4013 --output-zip 10fold_b_zip/10fold_10_uniter_mlm_tag_mean_kl_roformer.zip --output-json 10fold_b_json/10fold_10_uniter_mlm_tag_mean_kl_roformer.json
# CUDA_VISIBLE_DEVICES=2 python inference_pair_uniter_roformer_b.py --bert-dir junnyu/roformer_chinese_base --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_11_uniter_mlm_tag_mean_kl_roformer/ckpt-4013 --output-zip 10fold_b_zip/10fold_11_uniter_mlm_tag_mean_kl_roformer.zip --output-json 10fold_b_json/10fold_11_uniter_mlm_tag_mean_kl_roformer.json

CUDA_VISIBLE_DEVICES=2 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_1_mix_roformer_asl/ckpt-3014 --output-zip 10fold_b_zip/10fold_1_mix_roformer_asl.zip --output-json 10fold_b_json/10fold_1_mix_roformer_asl.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_2_mix_roformer_asl/ckpt-3014 --output-zip 10fold_b_zip/10fold_2_mix_roformer_asl.zip --output-json 10fold_b_json/10fold_2_mix_roformer_asl.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_3_mix_roformer_asl/ckpt-3014 --output-zip 10fold_b_zip/10fold_3_mix_roformer_asl.zip --output-json 10fold_b_json/10fold_3_mix_roformer_asl.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_4_mix_roformer_asl/ckpt-3014 --output-zip 10fold_b_zip/10fold_4_mix_roformer_asl.zip --output-json 10fold_b_json/10fold_4_mix_roformer_asl.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_5_mix_roformer_asl/ckpt-3014 --output-zip 10fold_b_zip/10fold_5_mix_roformer_asl.zip --output-json 10fold_b_json/10fold_5_mix_roformer_asl.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_6_mix_roformer_asl/ckpt-3014 --output-zip 10fold_b_zip/10fold_6_mix_roformer_asl.zip --output-json 10fold_b_json/10fold_6_mix_roformer_asl.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_7_mix_roformer_asl/ckpt-3014 --output-zip 10fold_b_zip/10fold_7_mix_roformer_asl.zip --output-json 10fold_b_json/10fold_7_mix_roformer_asl.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_8_mix_roformer_asl/ckpt-3014 --output-zip 10fold_b_zip/10fold_8_mix_roformer_asl.zip --output-json 10fold_b_json/10fold_8_mix_roformer_asl.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_9_mix_roformer_asl/ckpt-3014 --output-zip 10fold_b_zip/10fold_9_mix_roformer_asl.zip --output-json 10fold_b_json/10fold_9_mix_roformer_asl.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_10_mix_roformer_asl/ckpt-3014 --output-zip 10fold_b_zip/10fold_10_mix_roformer_asl.zip --output-json 10fold_b_json/10fold_10_mix_roformer_asl.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_11_mix_roformer_asl/ckpt-3014 --output-zip 10fold_b_zip/10fold_11_mix_roformer_asl.zip --output-json 10fold_b_json/10fold_11_mix_roformer_asl.json