# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_1_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_1_mix_roformer_256.zip --output-json 10fold_b_json/10fold_1_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_2_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_2_mix_roformer_256.zip --output-json 10fold_b_json/10fold_2_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_3_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_3_mix_roformer_256.zip --output-json 10fold_b_json/10fold_3_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_4_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_4_mix_roformer_256.zip --output-json 10fold_b_json/10fold_4_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_5_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_5_mix_roformer_256.zip --output-json 10fold_b_json/10fold_5_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_6_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_6_mix_roformer_256.zip --output-json 10fold_b_json/10fold_6_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_7_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_7_mix_roformer_256.zip --output-json 10fold_b_json/10fold_7_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_8_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_8_mix_roformer_256.zip --output-json 10fold_b_json/10fold_8_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_9_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_9_mix_roformer_256.zip --output-json 10fold_b_json/10fold_9_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_10_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_10_mix_roformer_256.zip --output-json 10fold_b_json/10fold_10_mix_roformer_256.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_roformer_b.py --bert-dir junnyu/roformer_chinese_base --bert-seq-length 32 --ckpt-file save/10fold_11_mix_roformer_256/ckpt-4012 --output-zip 10fold_b_zip/10fold_11_mix_roformer_256.zip --output-json 10fold_b_json/10fold_11_mix_roformer_256.json

# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/ft_uniter_mlm_mean_3000/ckpt-3014 --output-zip 10fold_b_zip/10fold_1_uniter_mlm_mean.zip 

# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_1_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_1_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_1_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_2_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_2_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_2_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_3_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_3_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_3_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_4_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_4_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_4_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_5_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_5_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_5_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_6_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_6_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_6_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_7_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_7_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_7_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_8_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_8_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_8_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_9_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_9_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_9_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_10_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_10_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_10_uniter_mlm_tag_mean_kl.json
# CUDA_VISIBLE_DEVICES=3 python inference_pair_uniter_b.py --uniter-pooling mean --bert-seq-length 32 --ckpt-file save/10fold/10fold_11_uniter_mlm_tag_mean_kl/ckpt-3014 --output-zip 10fold_b_zip/10fold_11_uniter_mlm_tag_mean_kl.zip --output-json 10fold_b_json/10fold_11_uniter_mlm_tag_mean_kl.json

CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_1_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_1_mix_addtf.zip --output-json 10fold_b_json/10fold_1_mix_addtf.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_2_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_2_mix_addtf.zip --output-json 10fold_b_json/10fold_2_mix_addtf.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_3_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_3_mix_addtf.zip --output-json 10fold_b_json/10fold_3_mix_addtf.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_4_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_4_mix_addtf.zip --output-json 10fold_b_json/10fold_4_mix_addtf.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_5_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_5_mix_addtf.zip --output-json 10fold_b_json/10fold_5_mix_addtf.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_6_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_6_mix_addtf.zip --output-json 10fold_b_json/10fold_6_mix_addtf.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_7_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_7_mix_addtf.zip --output-json 10fold_b_json/10fold_7_mix_addtf.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_8_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_8_mix_addtf.zip --output-json 10fold_b_json/10fold_8_mix_addtf.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_9_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_9_mix_addtf.zip --output-json 10fold_b_json/10fold_9_mix_addtf.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_10_mix_addtf/ckpt-3014 --output-zip 10fold_b_zip/10fold_10_mix_addtf.zip --output-json 10fold_b_json/10fold_10_mix_addtf.json
CUDA_VISIBLE_DEVICES=2 python inference_pair_b.py --ckpt-file save/10fold/10fold_11_mix_addtf/ckpt-4012 --output-zip 10fold_b_zip/10fold_11_mix_addtf.zip --output-json 10fold_b_json/10fold_11_mix_addtf.json